updated cleanup job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -440,7 +440,7 @@ jobs:
               if curl -s "${Frontend_URL}" | grep "Welcome"
               then
                   # Change this to 0 after the job fails
-                exit 0
+                exit 1
               else
                 exit 1
               fi
@@ -461,7 +461,7 @@ jobs:
           name: install dependencies 
           command: |
             apk add --update --no-cache aws-cli curl nodejs npm
-
+          
       - run:
           name: Save Old Workflow ID to kvdb.io
           command: |
@@ -470,16 +470,16 @@ jobs:
               --no-paginate --output text)
             echo Old Workflow ID: "$OldWorkflowID"
             curl https://kvdb.io/${KVDB_BUCKET}/old_workflow_id -d "$OldWorkflowID"
+            
       - run:
           name: Update cloudfront distribution
           command: |
-            export OldWorkflowID=$(curl --insecure https://kvdb.io/${KVDB_BUCKET}/old_workflow_id)
-            echo Old Workflow ID: "$OldWorkflowID"
             aws cloudformation deploy \
             --template-file .circleci/files/cloudfront.yml \
             --stack-name InitialStack \
-            --parameter-overrides WorkflowID="udapeople-${CIRCLE_WORKFLOW_ID:0:7}"
+            --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}"
             echo Current Workflow ID: "${CIRCLE_WORKFLOW_ID:0:7}"
+            
       # Here's where you will add some code to rollback on failure
       - notify_on_success
       - notify_on_crash
@@ -502,20 +502,29 @@ jobs:
           name: Remove old stacks and files
           command: |
           
+            # Fetch the Old workflow ID
             export OldWorkflowID=$(aws cloudformation \
                       list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
                       --no-paginate --output text)
             echo OldWorkflowID: "${OldWorkflowID}"
             echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
+            
+            # Fetch bucket originally linked to cloudfront
+            Old_Bucket_ID=$(curl https://kvdb.io/${KVDB_BUCKET_ID}/old_workflow_id)
+            
             # Fetch the stack names          
             export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
                       --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
             echo Stack names: "${STACKS[@]}" 
             if [[ "${CIRCLE_WORKFLOW_ID:0:7}" =~ "${OldWorkflowID}" ]]
             then
+              echo "-----------------Delete Confirmed-------------------"
+              aws s3 rm "s3://Old_Bucket_ID" --recursive
               aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
               aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
               aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
+            else
+              echo "-----------------Failed Cleanup-----------------------------"
             fi
       - notify_on_success
       - notify_on_crash
